# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7e9d649665bb388904e95208ab4de89872f73c321dc5621b0011bb8e6f627847e295657c619e3ded010547c87abe1ab0e09056143df3929940341e62907231

test:
  secret_key_base: 699a7ab2dd9b0ee9de5f4addaf5a93c985a38c69562585be86cbfe44e28b983d85471012811fef14cbe466fc1bdd90f97f96f8c7edf34512c05c11cff1a7fdf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
